/**
 * Emits the system-library seed as idempotent SQL (§4.13).
 *
 * System rows (muscles, exercises, metric_definitions with user_id = null) are
 * seeded by migration under the service role, never through the API. Their ids
 * are the same readable slugs the client uses, so the server row and every
 * device's IndexedDB row share a primary key and upsert cleanly.
 *
 * **Do not overwrite 0004_seed_library.sql with this output.** That migration is
 * already applied, and it runs *before* 0013 collapsed `movement_pattern` to four
 * values — so replaying it with the new values would fail on an enum that doesn't
 * have them yet. Migration history is append-only. Emit to a NEW migration when
 * the library gains rows:
 *
 *   node --experimental-strip-types supabase/generate-seed.mjs \
 *     > supabase/migrations/00NN_seed_library_additions.sql
 *
 * The output is idempotent (`on conflict do nothing`), so re-seeding the whole
 * library in a later migration only inserts what's missing.
 *
 * Kept as a generator rather than hand-written SQL so the server library can
 * never drift from src/db/seed/ — there is one source of truth for the taxonomy.
 */

import { EXERCISE_SEEDS } from '../src/db/seed/exercises.ts'
import { MUSCLE_SEEDS } from '../src/db/seed/muscles.ts'
import { METRIC_SEEDS } from '../src/db/seed/metrics.ts'
import { patternForRegion } from '../src/domain/movement.ts'

/**
 * Movement pattern is derived from the primary muscle's region, exactly as the
 * client does it (`src/domain/movement.ts`), so the seeded rows and a locally
 * created exercise can never disagree.
 */
const REGION_BY_MUSCLE = new Map(MUSCLE_SEEDS.map((m) => [m.id, m.region]))
const patternFor = (muscleId) =>
  patternForRegion(REGION_BY_MUSCLE.get(muscleId) ?? 'core')

/** Must match slugify() in src/db/seed/index.ts exactly, or ids won't align. */
function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`
const arr = (items) => `array[${items.map(q).join(', ')}]::text[]`

const out = []
out.push('-- Generated by supabase/generate-seed.mjs — do not edit by hand.')
out.push('-- System library: muscles, exercises, metric definitions (user_id = null).')
out.push('-- Idempotent: on conflict do nothing, so re-running never duplicates.')
out.push('')

// Muscles ---------------------------------------------------------------------
out.push('insert into muscles (id, user_id, name, region) values')
out.push(
  MUSCLE_SEEDS.map((m) => `  (${q(m.id)}, null, ${q(m.name)}, ${q(m.region)})`).join(',\n') +
    '\non conflict (id) do nothing;',
)
out.push('')

// Exercises -------------------------------------------------------------------
out.push(
  'insert into exercises (id, user_id, name, primary_muscle_id, aliases, equipment,',
)
out.push('  movement_pattern, tracking_type, is_unilateral, bodyweight_factor) values')
out.push(
  EXERCISE_SEEDS.map((e) => {
    const id = slugify(e.name)
    return (
      `  (${q(id)}, null, ${q(e.name)}, ${q(e.primary)}, ` +
      `${arr(e.aliases ?? [])}, ${q(e.equipment)}, ${q(patternFor(e.primary))}, ` +
      `${q(e.tracking ?? 'weight_reps')}, ${e.unilateral ?? false}, ` +
      `${e.bodyweightFactor ?? 'null'})`
    )
  }).join(',\n') + '\non conflict (id) do nothing;',
)
out.push('')

// Metric definitions ----------------------------------------------------------
out.push(
  'insert into metric_definitions (id, user_id, key, label, unit_type, category,',
)
out.push('  higher_is_better, aggregation, precision) values')
out.push(
  METRIC_SEEDS.map(
    (m) =>
      `  (${q(m.key)}, null, ${q(m.key)}, ${q(m.label)}, ${q(m.unitType)}, ` +
      `${q(m.category)}, ${m.higherIsBetter === null ? 'null' : m.higherIsBetter}, ` +
      `'last', ${m.precision})`,
  ).join(',\n') + '\non conflict (id) do nothing;',
)
out.push('')

process.stdout.write(out.join('\n') + '\n')
