/**
 * Emits the system-library seed as idempotent SQL (§4.13).
 *
 * System rows (exercises, metric_definitions with user_id = null) are seeded by
 * migration under the service role, never through the API. Their ids are the same
 * readable slugs the client uses, so the server row and every device's IndexedDB
 * row share a primary key and upsert cleanly.
 *
 * **Do not overwrite 0004_seed_library.sql with this output.** That migration is
 * already applied, and it runs *before* 0013 collapsed `movement_pattern` to four
 * values — so replaying it with the new values would fail on an enum that doesn't
 * have them yet. Migration history is append-only. Emit to a NEW migration when
 * the library gains rows:
 *
 *   node --experimental-strip-types supabase/generate-seed.mjs \
 *     > supabase/migrations/00NN_seed_library_additions.sql
 *
 * The output is idempotent (`on conflict do nothing`), so re-seeding the whole
 * library in a later migration only inserts what's missing.
 *
 * Kept as a generator rather than hand-written SQL so the server library can
 * never drift from src/db/seed/ — there is one source of truth for the taxonomy.
 */

import { EXERCISE_SEEDS } from '../src/db/seed/exercises.ts'
import { METRIC_SEEDS } from '../src/db/seed/metrics.ts'
import { movementFor, patternForRegion } from '../src/domain/movement.ts'

// The library is one row per base movement; equipment isn't stored on the
// exercise at all (it's chosen per workout). This derives the base rows from the
// per-variant seed the same way deriveBases() in src/db/seed/bases.ts does (kept
// inline because that module uses the `@/` alias, which plain node can't resolve).

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
}

const movementOf = (e) => e.movement ?? movementFor(e.name)

function deriveBases() {
  const grouped = new Map()
  for (const e of EXERCISE_SEEDS) {
    const label = movementOf(e)
    if (!grouped.has(label)) grouped.set(label, [])
    grouped.get(label).push(e)
  }
  return [...grouped.entries()].map(([label, vs]) => ({
    id: slugify(label),
    name: label,
    region: vs[0].region,
    aliases: [
      ...new Set([
        ...vs.flatMap((v) => v.aliases ?? []),
        ...vs.map((v) => v.name.toLowerCase()).filter((n) => n !== label.toLowerCase()),
      ]),
    ],
    tracking: vs[0].tracking ?? 'weight_reps',
    bodyweightFactor: vs[0].bodyweightFactor ?? null,
  }))
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`
const arr = (items) => `array[${items.map(q).join(', ')}]::text[]`

const out = []
out.push('-- Generated by supabase/generate-seed.mjs — do not edit by hand.')
out.push('-- System library: exercises, metric definitions (user_id = null).')
out.push('-- Idempotent: on conflict do nothing, so re-running never duplicates.')
out.push('')

// Exercises (base rows) -------------------------------------------------------
out.push(
  'insert into exercises (id, user_id, name, region, aliases, movement_pattern,',
)
out.push('  tracking_type, bodyweight_factor) values')
out.push(
  deriveBases()
    .map(
      (b) =>
        `  (${q(b.id)}, null, ${q(b.name)}, ${q(b.region)}, ${arr(b.aliases)}, ` +
        `${q(patternForRegion(b.region))}, ${q(b.tracking)}, ${b.bodyweightFactor ?? 'null'})`,
    )
    .join(',\n') + '\non conflict (id) do nothing;',
)
out.push('')

// Metric definitions ----------------------------------------------------------
out.push('insert into metric_definitions (id, user_id, key, label, unit_type, category,')
out.push('  higher_is_better, aggregation, precision) values')
out.push(
  METRIC_SEEDS.map(
    (m) =>
      `  (${q(m.key)}, null, ${q(m.key)}, ${q(m.label)}, ${q(m.unitType)}, ` +
      `${q(m.category)}, ${m.higherIsBetter === null ? 'null' : m.higherIsBetter}, ` +
      `'last', ${m.precision})`,
  ).join(',\n') + '\non conflict (id) do nothing;',
)
out.push('')

process.stdout.write(out.join('\n') + '\n')
