/**
 * The system exercise library (§4.3).
 *
 * Each row carries the taxonomy that makes charts work: a primary muscle,
 * weighted secondaries for partial volume credit, a movement pattern, and a
 * tracking type that decides which input UI the set row renders.
 *
 * `bodyweightFactor` is the fraction of bodyweight the movement actually
 * lifts — without it, a set of pull-ups registers as zero load.
 */

import type { Equipment, MovementPattern, TrackingType } from '@/domain/types'

export interface ExerciseSeed {
  name: string
  primary: string
  /** [muscleId, contribution] — partial credit toward that muscle's volume. */
  secondary?: [string, number][]
  equipment: Equipment
  pattern: MovementPattern
  /** Defaults to `weight_reps`, which covers most of the library. */
  tracking?: TrackingType
  bodyweightFactor?: number
  unilateral?: boolean
  aliases?: string[]
}

export const EXERCISE_SEEDS: ExerciseSeed[] = [
  // ---------------------------------------------------------------- chest
  {
    name: 'Barbell Bench Press',
    primary: 'mid_chest',
    secondary: [['front_delt', 0.5], ['triceps', 0.5]],
    equipment: 'barbell',
    pattern: 'horizontal_push',
    aliases: ['bench', 'flat bench', 'bb bench'],
  },
  {
    name: 'Incline Barbell Bench Press',
    primary: 'upper_chest',
    secondary: [['front_delt', 0.6], ['triceps', 0.4]],
    equipment: 'barbell',
    pattern: 'horizontal_push',
    aliases: ['incline bench'],
  },
  {
    name: 'Decline Barbell Bench Press',
    primary: 'lower_chest',
    secondary: [['triceps', 0.4]],
    equipment: 'barbell',
    pattern: 'horizontal_push',
  },
  {
    name: 'Dumbbell Bench Press',
    primary: 'mid_chest',
    secondary: [['front_delt', 0.5], ['triceps', 0.5]],
    equipment: 'dumbbell',
    pattern: 'horizontal_push',
    aliases: ['db bench'],
  },
  {
    name: 'Incline Dumbbell Bench Press',
    primary: 'upper_chest',
    secondary: [['front_delt', 0.6], ['triceps', 0.4]],
    equipment: 'dumbbell',
    pattern: 'horizontal_push',
    aliases: ['incline db press'],
  },
  {
    name: 'Dumbbell Fly',
    primary: 'mid_chest',
    secondary: [['front_delt', 0.3]],
    equipment: 'dumbbell',
    pattern: 'isolation',
  },
  {
    name: 'Cable Fly',
    primary: 'mid_chest',
    secondary: [['front_delt', 0.3]],
    equipment: 'cable',
    pattern: 'isolation',
    aliases: ['cable crossover'],
  },
  {
    name: 'Low-to-High Cable Fly',
    primary: 'upper_chest',
    secondary: [['front_delt', 0.3]],
    equipment: 'cable',
    pattern: 'isolation',
  },
  {
    name: 'Pec Deck',
    primary: 'mid_chest',
    equipment: 'machine',
    pattern: 'isolation',
    aliases: ['machine fly'],
  },
  {
    name: 'Chest Press Machine',
    primary: 'mid_chest',
    secondary: [['front_delt', 0.4], ['triceps', 0.4]],
    equipment: 'machine',
    pattern: 'horizontal_push',
  },
  {
    name: 'Smith Machine Bench Press',
    primary: 'mid_chest',
    secondary: [['front_delt', 0.4], ['triceps', 0.5]],
    equipment: 'smith',
    pattern: 'horizontal_push',
  },
  {
    name: 'Push-up',
    primary: 'mid_chest',
    secondary: [['front_delt', 0.4], ['triceps', 0.5], ['rectus_abdominis', 0.2]],
    equipment: 'bodyweight',
    pattern: 'horizontal_push',
    tracking: 'bodyweight_reps',
    bodyweightFactor: 0.64,
    aliases: ['pushup', 'press-up'],
  },
  {
    name: 'Dip',
    primary: 'lower_chest',
    secondary: [['triceps', 0.7], ['front_delt', 0.4]],
    equipment: 'bodyweight',
    pattern: 'horizontal_push',
    tracking: 'weighted_bodyweight',
    bodyweightFactor: 0.95,
    aliases: ['chest dip'],
  },
  {
    name: 'Assisted Dip',
    primary: 'lower_chest',
    secondary: [['triceps', 0.7], ['front_delt', 0.4]],
    equipment: 'machine',
    pattern: 'horizontal_push',
    tracking: 'assisted_bodyweight',
    bodyweightFactor: 0.95,
  },

  // ----------------------------------------------------------------- back
  {
    name: 'Deadlift',
    primary: 'erectors',
    secondary: [['glutes', 0.8], ['hamstrings', 0.8], ['lats', 0.4], ['upper_traps', 0.4], ['forearms', 0.3]],
    equipment: 'barbell',
    pattern: 'hinge',
    aliases: ['conventional deadlift', 'dl'],
  },
  {
    name: 'Sumo Deadlift',
    primary: 'glutes',
    secondary: [['quads', 0.6], ['erectors', 0.7], ['adductors', 0.5], ['upper_traps', 0.3]],
    equipment: 'barbell',
    pattern: 'hinge',
  },
  {
    name: 'Trap Bar Deadlift',
    primary: 'quads',
    secondary: [['glutes', 0.7], ['erectors', 0.6], ['upper_traps', 0.4]],
    equipment: 'barbell',
    pattern: 'hinge',
  },
  {
    name: 'Romanian Deadlift',
    primary: 'hamstrings',
    secondary: [['glutes', 0.7], ['erectors', 0.5]],
    equipment: 'barbell',
    pattern: 'hinge',
    aliases: ['rdl'],
  },
  {
    name: 'Barbell Row',
    primary: 'lats',
    secondary: [['rhomboids', 0.6], ['mid_traps', 0.6], ['biceps', 0.4], ['rear_delt', 0.4]],
    equipment: 'barbell',
    pattern: 'horizontal_pull',
    aliases: ['bent over row', 'bb row'],
  },
  {
    name: 'Pendlay Row',
    primary: 'lats',
    secondary: [['rhomboids', 0.6], ['mid_traps', 0.6], ['biceps', 0.4]],
    equipment: 'barbell',
    pattern: 'horizontal_pull',
  },
  {
    name: 'Dumbbell Row',
    primary: 'lats',
    secondary: [['rhomboids', 0.5], ['biceps', 0.4], ['rear_delt', 0.3]],
    equipment: 'dumbbell',
    pattern: 'horizontal_pull',
    unilateral: true,
    aliases: ['one arm row', 'db row'],
  },
  {
    name: 'Seated Cable Row',
    primary: 'lats',
    secondary: [['rhomboids', 0.6], ['mid_traps', 0.5], ['biceps', 0.4]],
    equipment: 'cable',
    pattern: 'horizontal_pull',
    aliases: ['cable row'],
  },
  {
    name: 'Chest-Supported Row',
    primary: 'rhomboids',
    secondary: [['lats', 0.7], ['mid_traps', 0.6], ['rear_delt', 0.4], ['biceps', 0.3]],
    equipment: 'machine',
    pattern: 'horizontal_pull',
  },
  {
    name: 'T-Bar Row',
    primary: 'lats',
    secondary: [['rhomboids', 0.6], ['mid_traps', 0.5], ['biceps', 0.4]],
    equipment: 'barbell',
    pattern: 'horizontal_pull',
  },
  {
    name: 'Inverted Row',
    primary: 'lats',
    secondary: [['rhomboids', 0.6], ['biceps', 0.4], ['rear_delt', 0.3]],
    equipment: 'bodyweight',
    pattern: 'horizontal_pull',
    tracking: 'weighted_bodyweight',
    bodyweightFactor: 0.55,
  },
  {
    name: 'Pull-up',
    primary: 'lats',
    secondary: [['biceps', 0.5], ['rhomboids', 0.4], ['teres', 0.4], ['lower_traps', 0.3]],
    equipment: 'bodyweight',
    pattern: 'vertical_pull',
    tracking: 'weighted_bodyweight',
    bodyweightFactor: 1.0,
    aliases: ['pullup'],
  },
  {
    name: 'Chin-up',
    primary: 'lats',
    secondary: [['biceps', 0.7], ['brachialis', 0.4], ['rhomboids', 0.3]],
    equipment: 'bodyweight',
    pattern: 'vertical_pull',
    tracking: 'weighted_bodyweight',
    bodyweightFactor: 1.0,
    aliases: ['chinup'],
  },
  {
    name: 'Assisted Pull-up',
    primary: 'lats',
    secondary: [['biceps', 0.5], ['rhomboids', 0.4]],
    equipment: 'machine',
    pattern: 'vertical_pull',
    tracking: 'assisted_bodyweight',
    bodyweightFactor: 1.0,
  },
  {
    name: 'Lat Pulldown',
    primary: 'lats',
    secondary: [['biceps', 0.4], ['rhomboids', 0.4], ['teres', 0.3]],
    equipment: 'cable',
    pattern: 'vertical_pull',
    aliases: ['pulldown'],
  },
  {
    name: 'Close-Grip Lat Pulldown',
    primary: 'lats',
    secondary: [['biceps', 0.5], ['brachialis', 0.3]],
    equipment: 'cable',
    pattern: 'vertical_pull',
  },
  {
    name: 'Straight-Arm Pulldown',
    primary: 'lats',
    secondary: [['teres', 0.4]],
    equipment: 'cable',
    pattern: 'isolation',
  },
  {
    name: 'Barbell Shrug',
    primary: 'upper_traps',
    secondary: [['forearms', 0.3]],
    equipment: 'barbell',
    pattern: 'isolation',
  },
  {
    name: 'Dumbbell Shrug',
    primary: 'upper_traps',
    secondary: [['forearms', 0.3]],
    equipment: 'dumbbell',
    pattern: 'isolation',
  },
  {
    name: 'Back Extension',
    primary: 'erectors',
    secondary: [['glutes', 0.5], ['hamstrings', 0.4]],
    equipment: 'bodyweight',
    pattern: 'hinge',
    tracking: 'weighted_bodyweight',
    bodyweightFactor: 0.5,
    aliases: ['hyperextension'],
  },
  {
    name: 'Rack Pull',
    primary: 'erectors',
    secondary: [['glutes', 0.5], ['upper_traps', 0.5], ['lats', 0.3]],
    equipment: 'barbell',
    pattern: 'hinge',
  },

  // ------------------------------------------------------------ shoulders
  {
    name: 'Overhead Press',
    primary: 'front_delt',
    secondary: [['side_delt', 0.5], ['triceps', 0.6], ['upper_traps', 0.3]],
    equipment: 'barbell',
    pattern: 'vertical_push',
    aliases: ['ohp', 'military press', 'standing press'],
  },
  {
    name: 'Seated Dumbbell Shoulder Press',
    primary: 'front_delt',
    secondary: [['side_delt', 0.5], ['triceps', 0.5]],
    equipment: 'dumbbell',
    pattern: 'vertical_push',
    aliases: ['db shoulder press'],
  },
  {
    name: 'Arnold Press',
    primary: 'front_delt',
    secondary: [['side_delt', 0.6], ['triceps', 0.4]],
    equipment: 'dumbbell',
    pattern: 'vertical_push',
  },
  {
    name: 'Machine Shoulder Press',
    primary: 'front_delt',
    secondary: [['side_delt', 0.4], ['triceps', 0.5]],
    equipment: 'machine',
    pattern: 'vertical_push',
  },
  {
    name: 'Dumbbell Lateral Raise',
    primary: 'side_delt',
    secondary: [['upper_traps', 0.2]],
    equipment: 'dumbbell',
    pattern: 'isolation',
    aliases: ['side raise', 'lat raise'],
  },
  {
    name: 'Cable Lateral Raise',
    primary: 'side_delt',
    equipment: 'cable',
    pattern: 'isolation',
    unilateral: true,
  },
  {
    name: 'Machine Lateral Raise',
    primary: 'side_delt',
    equipment: 'machine',
    pattern: 'isolation',
  },
  {
    name: 'Reverse Dumbbell Fly',
    primary: 'rear_delt',
    secondary: [['rhomboids', 0.5], ['mid_traps', 0.4]],
    equipment: 'dumbbell',
    pattern: 'isolation',
    aliases: ['rear delt fly', 'reverse chest fly', 'bent over fly'],
  },
  {
    name: 'Reverse Pec Deck',
    primary: 'rear_delt',
    secondary: [['rhomboids', 0.5], ['mid_traps', 0.4]],
    equipment: 'machine',
    pattern: 'isolation',
    aliases: ['reverse fly machine'],
  },
  {
    name: 'Face Pull',
    primary: 'rear_delt',
    secondary: [['mid_traps', 0.5], ['rhomboids', 0.5], ['lower_traps', 0.4]],
    equipment: 'cable',
    pattern: 'horizontal_pull',
  },
  {
    name: 'Front Raise',
    primary: 'front_delt',
    equipment: 'dumbbell',
    pattern: 'isolation',
  },
  {
    name: 'Upright Row',
    primary: 'side_delt',
    secondary: [['upper_traps', 0.6], ['biceps', 0.3]],
    equipment: 'barbell',
    pattern: 'vertical_pull',
  },

  // ----------------------------------------------------------------- arms
  {
    name: 'Barbell Curl',
    primary: 'biceps',
    secondary: [['brachialis', 0.4], ['forearms', 0.3]],
    equipment: 'barbell',
    pattern: 'isolation',
    aliases: ['bb curl'],
  },
  {
    name: 'Dumbbell Curl',
    primary: 'biceps',
    secondary: [['brachialis', 0.4], ['forearms', 0.3]],
    equipment: 'dumbbell',
    pattern: 'isolation',
    aliases: ['db curl'],
  },
  {
    name: 'Incline Dumbbell Curl',
    primary: 'biceps',
    secondary: [['brachialis', 0.3]],
    equipment: 'dumbbell',
    pattern: 'isolation',
  },
  {
    name: 'Hammer Curl',
    primary: 'brachialis',
    secondary: [['biceps', 0.7], ['forearms', 0.4]],
    equipment: 'dumbbell',
    pattern: 'isolation',
  },
  {
    name: 'Preacher Curl',
    primary: 'biceps',
    secondary: [['brachialis', 0.3]],
    equipment: 'barbell',
    pattern: 'isolation',
  },
  {
    name: 'Cable Curl',
    primary: 'biceps',
    secondary: [['brachialis', 0.3], ['forearms', 0.3]],
    equipment: 'cable',
    pattern: 'isolation',
  },
  {
    name: 'Concentration Curl',
    primary: 'biceps',
    equipment: 'dumbbell',
    pattern: 'isolation',
    unilateral: true,
  },
  {
    name: 'Close-Grip Bench Press',
    primary: 'triceps',
    secondary: [['mid_chest', 0.6], ['front_delt', 0.4]],
    equipment: 'barbell',
    pattern: 'horizontal_push',
  },
  {
    name: 'Skull Crusher',
    primary: 'triceps',
    equipment: 'barbell',
    pattern: 'isolation',
    aliases: ['lying triceps extension'],
  },
  {
    name: 'Cable Triceps Pushdown',
    primary: 'triceps',
    equipment: 'cable',
    pattern: 'isolation',
    aliases: ['tricep pushdown', 'rope pushdown'],
  },
  {
    name: 'Overhead Cable Triceps Extension',
    primary: 'triceps',
    equipment: 'cable',
    pattern: 'isolation',
  },
  {
    name: 'Dumbbell Overhead Triceps Extension',
    primary: 'triceps',
    equipment: 'dumbbell',
    pattern: 'isolation',
  },
  {
    name: 'Triceps Dip',
    primary: 'triceps',
    secondary: [['lower_chest', 0.5], ['front_delt', 0.3]],
    equipment: 'bodyweight',
    pattern: 'horizontal_push',
    tracking: 'weighted_bodyweight',
    bodyweightFactor: 0.9,
  },
  {
    name: 'Wrist Curl',
    primary: 'forearms',
    equipment: 'dumbbell',
    pattern: 'isolation',
  },
  {
    name: 'Reverse Wrist Curl',
    primary: 'forearms',
    equipment: 'dumbbell',
    pattern: 'isolation',
  },
  {
    name: 'Farmer Carry',
    primary: 'forearms',
    secondary: [['upper_traps', 0.6], ['rectus_abdominis', 0.4], ['obliques', 0.4]],
    equipment: 'dumbbell',
    pattern: 'carry',
    tracking: 'weight_time',
  },

  // ----------------------------------------------------------------- legs
  {
    name: 'Barbell Back Squat',
    primary: 'quads',
    secondary: [['glutes', 0.7], ['erectors', 0.5], ['adductors', 0.4], ['hamstrings', 0.3]],
    equipment: 'barbell',
    pattern: 'squat',
    aliases: ['squat', 'back squat'],
  },
  {
    name: 'Front Squat',
    primary: 'quads',
    secondary: [['glutes', 0.5], ['erectors', 0.5], ['rectus_abdominis', 0.3]],
    equipment: 'barbell',
    pattern: 'squat',
  },
  {
    name: 'Hack Squat',
    primary: 'quads',
    secondary: [['glutes', 0.5]],
    equipment: 'machine',
    pattern: 'squat',
  },
  {
    name: 'Leg Press',
    primary: 'quads',
    secondary: [['glutes', 0.6], ['hamstrings', 0.3]],
    equipment: 'machine',
    pattern: 'squat',
  },
  {
    name: 'Goblet Squat',
    primary: 'quads',
    secondary: [['glutes', 0.5], ['rectus_abdominis', 0.3]],
    equipment: 'kettlebell',
    pattern: 'squat',
  },
  {
    name: 'Bulgarian Split Squat',
    primary: 'quads',
    secondary: [['glutes', 0.8], ['adductors', 0.4], ['hamstrings', 0.3]],
    equipment: 'dumbbell',
    pattern: 'lunge',
    unilateral: true,
    aliases: ['bss', 'rear foot elevated split squat'],
  },
  {
    name: 'Walking Lunge',
    primary: 'quads',
    secondary: [['glutes', 0.7], ['hamstrings', 0.3], ['adductors', 0.3]],
    equipment: 'dumbbell',
    pattern: 'lunge',
  },
  {
    name: 'Reverse Lunge',
    primary: 'glutes',
    secondary: [['quads', 0.7], ['hamstrings', 0.4]],
    equipment: 'dumbbell',
    pattern: 'lunge',
    unilateral: true,
  },
  {
    name: 'Step-up',
    primary: 'quads',
    secondary: [['glutes', 0.7]],
    equipment: 'dumbbell',
    pattern: 'lunge',
    unilateral: true,
  },
  {
    name: 'Leg Extension',
    primary: 'quads',
    equipment: 'machine',
    pattern: 'isolation',
  },
  {
    name: 'Lying Leg Curl',
    primary: 'hamstrings',
    secondary: [['calves', 0.2]],
    equipment: 'machine',
    pattern: 'isolation',
  },
  {
    name: 'Seated Leg Curl',
    primary: 'hamstrings',
    equipment: 'machine',
    pattern: 'isolation',
  },
  {
    name: 'Nordic Hamstring Curl',
    primary: 'hamstrings',
    secondary: [['glutes', 0.3]],
    equipment: 'bodyweight',
    pattern: 'isolation',
    tracking: 'bodyweight_reps',
    bodyweightFactor: 0.6,
  },
  {
    name: 'Hip Thrust',
    primary: 'glutes',
    secondary: [['hamstrings', 0.5], ['erectors', 0.3]],
    equipment: 'barbell',
    pattern: 'hinge',
  },
  {
    name: 'Glute Bridge',
    primary: 'glutes',
    secondary: [['hamstrings', 0.4]],
    equipment: 'bodyweight',
    pattern: 'hinge',
    tracking: 'weighted_bodyweight',
    bodyweightFactor: 0.4,
  },
  {
    name: 'Cable Kickback',
    primary: 'glutes',
    equipment: 'cable',
    pattern: 'isolation',
    unilateral: true,
  },
  {
    name: 'Hip Abduction Machine',
    primary: 'abductors',
    secondary: [['glutes', 0.4]],
    equipment: 'machine',
    pattern: 'isolation',
  },
  {
    name: 'Hip Adduction Machine',
    primary: 'adductors',
    equipment: 'machine',
    pattern: 'isolation',
  },
  {
    name: 'Standing Calf Raise',
    primary: 'calves',
    equipment: 'machine',
    pattern: 'isolation',
  },
  {
    name: 'Seated Calf Raise',
    primary: 'calves',
    equipment: 'machine',
    pattern: 'isolation',
  },
  {
    name: 'Kettlebell Swing',
    primary: 'glutes',
    secondary: [['hamstrings', 0.7], ['erectors', 0.5], ['side_delt', 0.2]],
    equipment: 'kettlebell',
    pattern: 'hinge',
  },

  // ----------------------------------------------------------------- core
  {
    name: 'Plank',
    primary: 'transverse_abdominis',
    secondary: [['rectus_abdominis', 0.7], ['obliques', 0.5]],
    equipment: 'bodyweight',
    pattern: 'isolation',
    tracking: 'time',
  },
  {
    name: 'Side Plank',
    primary: 'obliques',
    secondary: [['transverse_abdominis', 0.6]],
    equipment: 'bodyweight',
    pattern: 'isolation',
    tracking: 'time',
    unilateral: true,
  },
  {
    name: 'Hanging Leg Raise',
    primary: 'rectus_abdominis',
    secondary: [['obliques', 0.4], ['forearms', 0.3]],
    equipment: 'bodyweight',
    pattern: 'isolation',
    tracking: 'weighted_bodyweight',
    bodyweightFactor: 0.5,
  },
  {
    name: 'Cable Crunch',
    primary: 'rectus_abdominis',
    secondary: [['obliques', 0.3]],
    equipment: 'cable',
    pattern: 'isolation',
  },
  {
    name: 'Crunch',
    primary: 'rectus_abdominis',
    equipment: 'bodyweight',
    pattern: 'isolation',
    tracking: 'reps_only',
  },
  {
    name: 'Russian Twist',
    primary: 'obliques',
    secondary: [['rectus_abdominis', 0.4]],
    equipment: 'other',
    pattern: 'rotation',
  },
  {
    name: 'Cable Woodchop',
    primary: 'obliques',
    secondary: [['rectus_abdominis', 0.4], ['transverse_abdominis', 0.3]],
    equipment: 'cable',
    pattern: 'rotation',
    unilateral: true,
  },
  {
    name: 'Ab Wheel Rollout',
    primary: 'rectus_abdominis',
    secondary: [['transverse_abdominis', 0.7], ['lats', 0.3]],
    equipment: 'other',
    pattern: 'isolation',
    tracking: 'reps_only',
  },
  {
    name: 'Dead Bug',
    primary: 'transverse_abdominis',
    secondary: [['rectus_abdominis', 0.5]],
    equipment: 'bodyweight',
    pattern: 'isolation',
    tracking: 'reps_only',
  },
  {
    name: 'Pallof Press',
    primary: 'obliques',
    secondary: [['transverse_abdominis', 0.6]],
    equipment: 'cable',
    pattern: 'rotation',
    unilateral: true,
  },

  // --------------------------------------------------------------- cardio
  // distance_time gets a distance + duration input; time alone gets a timer.
  {
    name: 'Treadmill Run',
    primary: 'cardiovascular',
    equipment: 'machine',
    pattern: 'cardio',
    tracking: 'distance_time',
    aliases: ['treadmill'],
  },
  {
    name: 'Outdoor Run',
    primary: 'cardiovascular',
    equipment: 'other',
    pattern: 'cardio',
    tracking: 'distance_time',
    aliases: ['run', 'jog'],
  },
  {
    name: 'Treadmill Walk',
    primary: 'cardiovascular',
    equipment: 'machine',
    pattern: 'cardio',
    tracking: 'distance_time',
  },
  {
    name: 'Incline Walk',
    primary: 'cardiovascular',
    secondary: [['calves', 0.3], ['glutes', 0.3]],
    equipment: 'machine',
    pattern: 'cardio',
    tracking: 'distance_time',
  },
  {
    name: 'Stationary Bike',
    primary: 'cardiovascular',
    secondary: [['quads', 0.3]],
    equipment: 'machine',
    pattern: 'cardio',
    tracking: 'distance_time',
    aliases: ['bike', 'cycling'],
  },
  {
    name: 'Rowing Machine',
    primary: 'cardiovascular',
    secondary: [['lats', 0.3], ['quads', 0.3], ['erectors', 0.2]],
    equipment: 'machine',
    pattern: 'cardio',
    tracking: 'distance_time',
    aliases: ['erg', 'row'],
  },
  {
    name: 'Elliptical',
    primary: 'cardiovascular',
    equipment: 'machine',
    pattern: 'cardio',
    tracking: 'distance_time',
  },
  {
    name: 'Stair Climber',
    primary: 'cardiovascular',
    secondary: [['glutes', 0.3], ['calves', 0.3]],
    equipment: 'machine',
    pattern: 'cardio',
    tracking: 'time',
    aliases: ['stairmaster'],
  },
  {
    name: 'Swimming',
    primary: 'cardiovascular',
    secondary: [['lats', 0.3], ['front_delt', 0.2]],
    equipment: 'other',
    pattern: 'cardio',
    tracking: 'distance_time',
  },
  {
    name: 'Jump Rope',
    primary: 'cardiovascular',
    secondary: [['calves', 0.4]],
    equipment: 'other',
    pattern: 'cardio',
    tracking: 'time',
  },
  {
    name: 'Ruck',
    primary: 'cardiovascular',
    secondary: [['erectors', 0.3], ['upper_traps', 0.3]],
    equipment: 'other',
    pattern: 'cardio',
    tracking: 'distance_time',
  },
  {
    name: 'Assault Bike',
    primary: 'cardiovascular',
    equipment: 'machine',
    pattern: 'cardio',
    tracking: 'time',
  },
]
