-- Add a movement grouping slug to exercises, so the library and picker can
-- present one "Bench Press" with a barbell/dumbbell/smith chooser rather than
-- three separate rows. Additive and non-destructive: workout_exercises, sets,
-- and personal_records still key on the exercise id, so records and history
-- stay per (movement + equipment) with no re-keying.
--
-- The derivation strips one equipment word (barbell/dumbbell/cable/…) from the
-- name — grip and angle (Incline, Close-Grip) stay in the movement and mark a
-- distinct lift. Kept as a stored column, not a computed view, because two
-- library rows with the same computed name are legitimate ("Cable Crunch" is a
-- weighted movement, not the bodyweight "Crunch"), and users authoring a
-- custom exercise need to opt out of the default grouping.
--
-- The static CASE below is generated from EXERCISE_SEEDS via movementFor() in
-- src/domain/movement.ts (via supabase/generate-seed.mjs's audit) so server and
-- client can never disagree on the seeded rows. Anything not in the case (user
-- rows written pre-migration) gets a client-side repair on next launch — see
-- repairExerciseRows() in src/db/seed/index.ts.

alter table exercises add column movement text not null default '';

-- Seeded system rows get their explicit mapping.
update exercises e set movement = v.movement
from (values
  ('barbell_bench_press', 'Bench Press'),
  ('incline_barbell_bench_press', 'Incline Bench Press'),
  ('decline_barbell_bench_press', 'Decline Bench Press'),
  ('dumbbell_bench_press', 'Bench Press'),
  ('incline_dumbbell_bench_press', 'Incline Bench Press'),
  ('dumbbell_fly', 'Fly'),
  ('cable_fly', 'Fly'),
  ('low_to_high_cable_fly', 'Low-to-High Fly'),
  ('pec_deck', 'Pec Deck'),
  ('chest_press_machine', 'Chest Press'),
  ('smith_machine_bench_press', 'Bench Press'),
  ('push_up', 'Push-up'),
  ('dip', 'Dip'),
  ('assisted_dip', 'Assisted Dip'),
  ('deadlift', 'Deadlift'),
  ('sumo_deadlift', 'Sumo Deadlift'),
  ('trap_bar_deadlift', 'Trap Bar Deadlift'),
  ('romanian_deadlift', 'Romanian Deadlift'),
  ('barbell_row', 'Row'),
  ('pendlay_row', 'Pendlay Row'),
  ('dumbbell_row', 'Row'),
  ('seated_cable_row', 'Seated Row'),
  ('chest_supported_row', 'Chest-Supported Row'),
  ('t_bar_row', 'T-Bar Row'),
  ('inverted_row', 'Inverted Row'),
  ('pull_up', 'Pull-up'),
  ('chin_up', 'Chin-up'),
  ('assisted_pull_up', 'Assisted Pull-up'),
  ('lat_pulldown', 'Lat Pulldown'),
  ('close_grip_lat_pulldown', 'Close-Grip Lat Pulldown'),
  ('straight_arm_pulldown', 'Straight-Arm Pulldown'),
  ('barbell_shrug', 'Shrug'),
  ('dumbbell_shrug', 'Shrug'),
  ('back_extension', 'Back Extension'),
  ('rack_pull', 'Rack Pull'),
  ('overhead_press', 'Overhead Press'),
  ('seated_dumbbell_shoulder_press', 'Seated Shoulder Press'),
  ('arnold_press', 'Arnold Press'),
  ('machine_shoulder_press', 'Shoulder Press'),
  ('dumbbell_lateral_raise', 'Lateral Raise'),
  ('cable_lateral_raise', 'Lateral Raise'),
  ('machine_lateral_raise', 'Lateral Raise'),
  ('reverse_dumbbell_fly', 'Reverse Fly'),
  ('reverse_pec_deck', 'Reverse Pec Deck'),
  ('face_pull', 'Face Pull'),
  ('front_raise', 'Front Raise'),
  ('upright_row', 'Upright Row'),
  ('barbell_curl', 'Curl'),
  ('dumbbell_curl', 'Curl'),
  ('incline_dumbbell_curl', 'Incline Curl'),
  ('hammer_curl', 'Hammer Curl'),
  ('preacher_curl', 'Preacher Curl'),
  ('cable_curl', 'Curl'),
  ('concentration_curl', 'Concentration Curl'),
  ('close_grip_bench_press', 'Close-Grip Bench Press'),
  ('skull_crusher', 'Skull Crusher'),
  ('cable_triceps_pushdown', 'Triceps Pushdown'),
  ('overhead_cable_triceps_extension', 'Overhead Triceps Extension'),
  ('dumbbell_overhead_triceps_extension', 'Overhead Triceps Extension'),
  ('triceps_dip', 'Triceps Dip'),
  ('wrist_curl', 'Wrist Curl'),
  ('reverse_wrist_curl', 'Reverse Wrist Curl'),
  ('farmer_carry', 'Farmer Carry'),
  ('barbell_back_squat', 'Back Squat'),
  ('front_squat', 'Front Squat'),
  ('hack_squat', 'Hack Squat'),
  ('leg_press', 'Leg Press'),
  ('goblet_squat', 'Goblet Squat'),
  ('bulgarian_split_squat', 'Bulgarian Split Squat'),
  ('walking_lunge', 'Walking Lunge'),
  ('reverse_lunge', 'Reverse Lunge'),
  ('step_up', 'Step-up'),
  ('leg_extension', 'Leg Extension'),
  ('lying_leg_curl', 'Lying Leg Curl'),
  ('seated_leg_curl', 'Seated Leg Curl'),
  ('nordic_hamstring_curl', 'Nordic Hamstring Curl'),
  ('hip_thrust', 'Hip Thrust'),
  ('glute_bridge', 'Glute Bridge'),
  ('cable_kickback', 'Kickback'),
  ('hip_abduction_machine', 'Hip Abduction'),
  ('hip_adduction_machine', 'Hip Adduction'),
  ('standing_calf_raise', 'Standing Calf Raise'),
  ('seated_calf_raise', 'Seated Calf Raise'),
  ('kettlebell_swing', 'Swing'),
  ('plank', 'Plank'),
  ('side_plank', 'Side Plank'),
  ('hanging_leg_raise', 'Hanging Leg Raise'),
  ('cable_crunch', 'Cable Crunch'),
  ('crunch', 'Crunch'),
  ('russian_twist', 'Russian Twist'),
  ('cable_woodchop', 'Woodchop'),
  ('ab_wheel_rollout', 'Ab Wheel Rollout'),
  ('dead_bug', 'Dead Bug'),
  ('pallof_press', 'Pallof Press'),
  ('treadmill_run', 'Treadmill Run'),
  ('outdoor_run', 'Outdoor Run'),
  ('treadmill_walk', 'Treadmill Walk'),
  ('incline_walk', 'Incline Walk'),
  ('stationary_bike', 'Stationary Bike'),
  ('rowing_machine', 'Rowing'),
  ('elliptical', 'Elliptical'),
  ('stair_climber', 'Stair Climber'),
  ('swimming', 'Swimming'),
  ('jump_rope', 'Jump Rope'),
  ('ruck', 'Ruck'),
  ('assault_bike', 'Assault Bike'),
  ('machine_chest_fly', 'Chest Fly'),
  ('incline_cable_fly', 'Incline Fly'),
  ('incline_machine_press', 'Incline Press'),
  ('svend_press', 'Svend Press'),
  ('wide_grip_pull_up', 'Wide-Grip Pull-up'),
  ('neutral_grip_pulldown', 'Neutral-Grip Pulldown'),
  ('single_arm_dumbbell_row', 'Single-Arm Row'),
  ('meadows_row', 'Meadows Row'),
  ('seal_row', 'Seal Row'),
  ('machine_row', 'Row'),
  ('machine_pullover', 'Pullover'),
  ('good_morning', 'Good Morning'),
  ('push_press', 'Push Press'),
  ('seated_barbell_overhead_press', 'Seated Overhead Press'),
  ('landmine_press', 'Landmine Press'),
  ('cable_rear_delt_fly', 'Rear Delt Fly'),
  ('leaning_cable_lateral_raise', 'Leaning Lateral Raise'),
  ('plate_front_raise', 'Plate Front Raise'),
  ('ez_bar_curl', 'EZ-Bar Curl'),
  ('spider_curl', 'Spider Curl'),
  ('cable_rope_hammer_curl', 'Rope Hammer Curl'),
  ('bayesian_cable_curl', 'Bayesian Curl'),
  ('dumbbell_skull_crusher', 'Skull Crusher'),
  ('rope_overhead_extension', 'Rope Overhead Extension'),
  ('bench_dip', 'Bench Dip'),
  ('reverse_curl', 'Reverse Curl'),
  ('behind_the_back_wrist_curl', 'Behind-the-Back Wrist Curl'),
  ('pause_squat', 'Pause Squat'),
  ('box_squat', 'Box Squat'),
  ('belt_squat', 'Belt Squat'),
  ('sissy_squat', 'Sissy Squat'),
  ('single_leg_press', 'Single-Leg Press'),
  ('stiff_leg_deadlift', 'Stiff-Leg Deadlift'),
  ('single_leg_romanian_deadlift', 'Single-Leg Romanian Deadlift'),
  ('standing_leg_curl', 'Standing Leg Curl'),
  ('cable_pull_through', 'Pull-Through'),
  ('curtsy_lunge', 'Curtsy Lunge'),
  ('leg_press_calf_raise', 'Leg Press Calf Raise'),
  ('donkey_calf_raise', 'Donkey Calf Raise'),
  ('toes_to_bar', 'Toes-to-Bar'),
  ('weighted_plank', 'Weighted Plank'),
  ('decline_sit_up', 'Decline Sit-up'),
  ('bicycle_crunch', 'Bicycle Crunch'),
  ('hanging_knee_raise', 'Hanging Knee Raise'),
  ('landmine_rotation', 'Landmine Rotation'),
  ('copenhagen_plank', 'Copenhagen Plank'),
  ('sled_push', 'Sled Push'),
  ('battle_ropes', 'Battle Ropes'),
  ('box_jump', 'Box Jump'),
  ('burpee', 'Burpee'),
  ('power_clean', 'Power Clean'),
  ('hang_clean', 'Hang Clean'),
  ('clean_and_jerk', 'Clean and Jerk'),
  ('snatch', 'Snatch'),
  ('power_snatch', 'Power Snatch'),
  ('clean_pull', 'Clean Pull'),
  ('thruster', 'Thruster'),
  ('wall_ball', 'Wall Ball'),
  ('atlas_stone_lift', 'Atlas Stone Lift'),
  ('yoke_carry', 'Yoke Carry'),
  ('log_press', 'Log Press'),
  ('sandbag_carry', 'Sandbag Carry'),
  ('suitcase_carry', 'Suitcase Carry'),
  ('tire_flip', 'Tire Flip'),
  ('guillotine_press', 'Guillotine Press'),
  ('floor_press', 'Floor Press'),
  ('deficit_push_up', 'Deficit Push-up'),
  ('pendlay_deficit_row', 'Pendlay Deficit Row'),
  ('kroc_row', 'Kroc Row'),
  ('gorilla_row', 'Gorilla Row'),
  ('rope_face_pull', 'Rope Face Pull'),
  ('kneeling_lat_pulldown', 'Kneeling Lat Pulldown'),
  ('deadlift_snatch_grip', 'Deadlift (Snatch Grip)'),
  ('z_press', 'Z Press'),
  ('viking_press', 'Viking Press'),
  ('cable_upright_row', 'Upright Row'),
  ('machine_reverse_fly', 'Reverse Fly'),
  ('lu_raise', 'Lu Raise'),
  ('zottman_curl', 'Zottman Curl'),
  ('drag_curl', 'Drag Curl'),
  ('cross_body_hammer_curl', 'Cross-Body Hammer Curl'),
  ('jm_press', 'JM Press'),
  ('tate_press', 'Tate Press'),
  ('diamond_push_up', 'Diamond Push-up'),
  ('wrist_roller', 'Wrist Roller'),
  ('zercher_squat', 'Zercher Squat'),
  ('landmine_squat', 'Landmine Squat'),
  ('pistol_squat', 'Pistol Squat'),
  ('cossack_squat', 'Cossack Squat'),
  ('frog_pump', 'Frog Pump'),
  ('kettlebell_goblet_squat', 'Kettlebell Goblet Squat'),
  ('atg_split_squat', 'ATG Split Squat'),
  ('tibialis_raise', 'Tibialis Raise'),
  ('dragon_flag', 'Dragon Flag'),
  ('hollow_body_hold', 'Hollow Body Hold'),
  ('cable_pallof_hold', 'Pallof Hold'),
  ('weighted_decline_sit_up', 'Weighted Decline Sit-up'),
  ('l_sit', 'L-Sit'),
  ('mountain_climbers', 'Mountain Climbers'),
  ('high_knees', 'High Knees'),
  ('ski_erg', 'Ski Erg'),
  ('sled_drag', 'Sled Drag'),
  ('shadow_boxing', 'Shadow Boxing')
) as v(id, movement)
where e.id = v.id;

-- Any row not covered (user-authored rows) gets a safe placeholder equal to the
-- name; the client repair (repairExerciseRows) rewrites these to a proper
-- movement on next launch. Guarantees `movement <> ''` post-migration.
update exercises set movement = name where movement = '';

-- Enforce the invariant: no exercise without a movement.
alter table exercises add constraint exercises_movement_not_empty
  check (length(movement) > 0);

-- Group scans in the library go through this index.
create index exercises_movement on exercises (movement);
