import { syncStamp } from '@tracker-engine/local-first'
import * as repo from '@/data/repository'

/**
 * The foods shipped with the app.
 *
 * Two lists, loaded lazily, for two different reasons.
 *
 * **Two lists** because they have different lifecycles: `foods.ts` is regenerated by
 * scripts/build-food-seed.mjs, while `staples.ts` is hand-written and referred to by exact
 * description from the demo data, so it has to survive a re-run.
 *
 * **Lazily** because together they are over a megabyte of JSON. Inlined, that sat in the main bundle
 * and was parsed on every single load — including for the overwhelming majority of launches, where
 * the foods are already in IndexedDB and nothing needs to be read at all. A dynamic import makes it
 * a separate cacheable chunk that a returning user never fetches.
 */

/**
 * Bump when the seed is regenerated.
 *
 * `bulkPut` on every launch is what ships a corrected row to an existing install, and that mattered
 * more than the cost when the seed was 46 hand-written foods. At two thousand it is megabytes of parse on
 * every open to usually change nothing — so the version is compared instead, and the payload is only
 * fetched when it has actually moved.
 *
 * v4 backfills the staples' micronutrients (scripts/fill-staple-micros.mjs). They had only macros and
 * fibre, and being short clean descriptions they *outrank* the fuller USDA rows for the queries people
 * type most — so the app's most-logged foods were its least complete, and a day built from them
 * reported six of seven nutrients as unrecorded.
 *
 * v5 widens the generated seed from 1,463 foods to 2,166: 404 queries rather than 260, aimed at the
 * gaps a month of logging finds.
 */
const SEED_VERSION = 5
const VERSION_KEY = 'macros.seed.version'

export async function seedFoods(): Promise<number> {
  const stored = Number(localStorage.getItem(VERSION_KEY) ?? 0)
  if (stored === SEED_VERSION) return 0

  const [{ SEED_FOODS }, { STAPLE_FOODS }] = await Promise.all([
    import('./foods'),
    import('./staples'),
  ])
  // Staples last, so they win a `bulkPut` on id collision: a hand-verified row beats a generated one.
  const stamp = syncStamp()
  const foods = [...SEED_FOODS, ...STAPLE_FOODS].map((food) => ({ ...food, ...stamp }))
  // Through the repository, so the in-memory search index is invalidated the one place that owns it.
  await repo.putFoods(foods)
  localStorage.setItem(VERSION_KEY, String(SEED_VERSION))
  return foods.length
}
