/**
 * The AI coach screen (§13).
 *
 * Three things the user can ask for — a critique, a next-week plan, or a
 * freeform question — answered from the de-identified summary (§2). A plan is
 * never auto-applied: it's shown as editable-in-preview and only becomes
 * templates on an explicit "Save as templates". The "view the data sent"
 * disclosure shows exactly what left the device, because opt-in without
 * visibility isn't meaningful consent.
 *
 * Provider selection is automatic: the live Gemini provider is used when the
 * backend is reachable and the user is signed in, and every request falls back
 * to the offline mock if it's unavailable or errors — so the coach always
 * answers. The "generated by" line names whichever actually responded.
 */

import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import {
  ChevronLeft,
  Eye,
  Lightbulb,
  ListChecks,
  LogIn,
  MessageCircle,
  Sparkles,
} from 'lucide-react'
import * as repo from '@/data/repository'
import { useAuth } from '@/auth/AuthContext'
import { isBackendConfigured } from '@/sync/supabaseClient'
import { Button } from '@/components/Button'
import { Card } from '@/components/Card'
import { BottomSheet } from '@/components/BottomSheet'
import { useToast } from '@/components/Toast'
import { mockCoachProvider } from './mockProvider'
import { geminiCoachProvider } from './geminiProvider'
import type { CoachPlan, CoachRequest, CoachResponse } from './types'
import type { CoachSummary } from './summary'

export function CoachScreen({
  onBack,
  onOpenTemplates,
  onSignIn,
}: {
  onBack: () => void
  onOpenTemplates: () => void
  /** Take a local/offline user to the sign-in screen for the smarter live coach. */
  onSignIn: () => void
}) {
  const toast = useToast()
  const { session } = useAuth()
  const summary = useLiveQuery(() => repo.getCoachSummary(), [])
  // The live (Gemini) coach needs a real, server-backed session. With a backend
  // configured but the user on the offline "this device only" account, say so —
  // the coach still works (offline heuristics), just less cleverly.
  const canUseLiveCoach = isBackendConfigured() && session != null && !session.isLocal
  const [response, setResponse] = useState<CoachResponse | null>(null)
  const [pending, setPending] = useState<'critique' | 'plan' | 'ask' | null>(null)
  // Which free-text composer is open (goal for plan, question for ask), and its
  // current text. A single input serves both.
  const [composer, setComposer] = useState<'plan' | 'ask' | null>(null)
  const [composerText, setComposerText] = useState('')
  const [showData, setShowData] = useState(false)
  const [saving, setSaving] = useState(false)
  // Which provider actually answered, for the "generated by" line. The live
  // provider is used when reachable; every request falls back to the offline
  // mock if it throws, so the coach always answers.
  const [answeredBy, setAnsweredBy] = useState(mockCoachProvider.name)

  async function ask(request: CoachRequest) {
    if (!summary) return
    // The screen only issues critique/plan/ask; encouragement is Home-only.
    if (request.kind !== 'encouragement') setPending(request.kind)
    setResponse(null)
    try {
      const live = await geminiCoachProvider.isAvailable()
      if (live) {
        try {
          const result = await geminiCoachProvider.respond(summary, request)
          setAnsweredBy(geminiCoachProvider.name)
          setResponse(result)
          return
        } catch {
          // Live provider failed — fall through to the offline mock rather than
          // leaving the user with nothing.
          toast.show('Live coach unavailable — using the offline coach')
        }
      }
      setAnsweredBy(mockCoachProvider.name)
      setResponse(await mockCoachProvider.respond(summary, request))
    } catch {
      toast.show('The coach could not respond — try again')
    } finally {
      setPending(null)
    }
  }

  async function savePlan(plan: CoachPlan) {
    if (!summary) return
    setSaving(true)
    try {
      const { templateIds, unmatched } = await repo.createTemplatesFromPlan({
        sessions: plan.sessions,
        unitWeight: summary.unitWeight,
        // A multi-week program groups its days under its name as a folder.
        folder: plan.programName,
      })
      toast.show(
        unmatched.length > 0
          ? `Saved ${templateIds.length} templates · skipped ${unmatched.length} unknown`
          : `Saved ${templateIds.length} templates`,
      )
      onOpenTemplates()
    } finally {
      setSaving(false)
    }
  }

  /** Run whatever the open composer is (a goal-driven plan, or an ask). */
  function submitComposer() {
    const text = composerText.trim()
    if (composer === 'plan') void ask({ kind: 'plan', goal: text })
    else if (composer === 'ask' && text) void ask({ kind: 'ask', question: text })
    setComposer(null)
    setComposerText('')
  }

  const empty = summary && summary.totalWorkouts === 0

  return (
    <div className="flex h-full flex-col">
      <header className="flex items-center gap-2 border-b border-line bg-surface px-2 py-2 pt-safe">
        <button
          onClick={onBack}
          aria-label="Back"
          className="flex size-10 items-center justify-center rounded-lg text-ink-secondary active:bg-sunken"
        >
          <ChevronLeft size={22} />
        </button>
        <h1 className="flex-1 text-[16px] font-semibold tracking-tight">Coach</h1>
        {summary && (
          <button
            onClick={() => setShowData(true)}
            className="flex items-center gap-1 pr-2 text-[12.5px] font-medium text-ink-muted active:opacity-60"
          >
            <Eye size={14} />
            Data sent
          </button>
        )}
      </header>

      <div className="flex-1 space-y-3 overflow-y-auto px-3 py-3">
        {/* Provenance + the standing caveat (§13: always a suggestion). */}
        <p className="px-1 text-[12px] text-ink-muted">
          Suggestions from {answeredBy}, based on a de-identified summary of your
          training. Always a starting point — never medical advice, never auto-applied.
        </p>

        {/* The live coach needs a signed-in account. Offer the upgrade explicitly
            rather than silently falling back, so it's clear why answers differ. */}
        {isBackendConfigured() && !canUseLiveCoach && (
          <button
            onClick={onSignIn}
            className="flex w-full items-start gap-3 rounded-2xl border border-accent/30 bg-accent-wash p-3.5 text-left active:opacity-80"
          >
            <span className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-full bg-accent text-white">
              <LogIn size={16} />
            </span>
            <span className="min-w-0 flex-1">
              <span className="block text-[13.5px] font-semibold text-ink">
                Sign in for the smarter AI coach
              </span>
              <span className="mt-0.5 block text-[12.5px] text-ink-secondary">
                You're on the offline coach now — it still critiques and drafts plans.
                Sign in with email to get AI-generated coaching tailored to your history.
              </span>
            </span>
          </button>
        )}

        <div className="grid grid-cols-3 gap-2">
          <ActionButton
            icon={<Lightbulb size={18} />}
            label="Critique"
            busy={pending === 'critique'}
            disabled={!summary || pending !== null}
            onClick={() => {
              setComposer(null)
              void ask({ kind: 'critique' })
            }}
          />
          <ActionButton
            icon={<ListChecks size={18} />}
            label="Plan"
            busy={pending === 'plan'}
            disabled={!summary || pending !== null}
            active={composer === 'plan'}
            onClick={() => {
              setComposerText('')
              setComposer((c) => (c === 'plan' ? null : 'plan'))
            }}
          />
          <ActionButton
            icon={<MessageCircle size={18} />}
            label="Ask"
            busy={pending === 'ask'}
            disabled={!summary || pending !== null}
            active={composer === 'ask'}
            onClick={() => {
              setComposerText('')
              setComposer((c) => (c === 'ask' ? null : 'ask'))
            }}
          />
        </div>

        {/* One composer for both Plan (a goal) and Ask (a question). */}
        {composer && (
          <Composer
            mode={composer}
            value={composerText}
            onChange={setComposerText}
            onSubmit={submitComposer}
          />
        )}

        {empty && (
          <Card className="p-5 text-center">
            <Sparkles size={24} className="mx-auto text-ink-muted" />
            <p className="mt-2 text-[15px] font-semibold">Nothing to coach yet</p>
            <p className="mt-1 text-[13.5px] text-ink-secondary">
              Log a few workouts and the coach can critique your balance and draft a plan
              from your history.
            </p>
          </Card>
        )}

        {response?.kind === 'critique' && (
          <Card className="p-4">
            <SectionLabel>What stands out</SectionLabel>
            <ul className="mt-2 space-y-1.5">
              {response.critique.observations.map((o, i) => (
                <li key={i} className="text-[14px] leading-snug">
                  {o}
                </li>
              ))}
            </ul>
            <SectionLabel className="mt-4">Suggestions</SectionLabel>
            <ul className="mt-2 space-y-1.5">
              {response.critique.suggestions.map((s, i) => (
                <li key={i} className="flex gap-2 text-[14px] leading-snug">
                  <span className="text-accent">→</span>
                  <span>{s}</span>
                </li>
              ))}
            </ul>
          </Card>
        )}

        {response?.kind === 'plan' && (
          <PlanView
            plan={response.plan}
            saving={saving}
            onSave={() => void savePlan(response.plan)}
          />
        )}

        {response?.kind === 'answer' && response.text && (
          <Card className="p-4">
            <p className="whitespace-pre-wrap text-[14px] leading-snug">
              {response.text}
            </p>
          </Card>
        )}
      </div>

      {showData && summary && (
        <DataDisclosure summary={summary} onDismiss={() => setShowData(false)} />
      )}
    </div>
  )
}

function ActionButton({
  icon,
  label,
  busy,
  disabled,
  active = false,
  onClick,
}: {
  icon: React.ReactNode
  label: string
  busy: boolean
  disabled: boolean
  active?: boolean
  onClick: () => void
}) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={
        'flex flex-col items-center gap-1 rounded-xl border py-3 text-[12.5px] font-semibold disabled:opacity-40 ' +
        (active
          ? 'border-accent bg-accent-wash'
          : 'border-line bg-surface active:bg-accent-wash')
      }
    >
      <span className="text-accent">{icon}</span>
      {busy ? 'Thinking…' : label}
    </button>
  )
}

/** The shared free-text box: a goal for Plan, a question for Ask. */
function Composer({
  mode,
  value,
  onChange,
  onSubmit,
}: {
  mode: 'plan' | 'ask'
  value: string
  onChange: (v: string) => void
  onSubmit: () => void
}) {
  const isPlan = mode === 'plan'
  return (
    <Card className="p-4">
      <SectionLabel>
        {isPlan ? 'Your goal (optional)' : 'Ask about your training'}
      </SectionLabel>
      <p className="mt-1 text-[12px] text-ink-muted">
        {isPlan
          ? 'e.g. "strength-focused 12-week program" or "hypertrophy, 4 days". Leave blank for a balanced next week.'
          : 'e.g. "what\'s my weakest area?" or "give me a push day".'}
      </p>
      <div className="mt-2 flex gap-2">
        <input
          autoFocus
          value={value}
          onChange={(event) => onChange(event.target.value)}
          placeholder={isPlan ? 'What are you training for?' : 'Ask anything'}
          className="h-11 min-w-0 flex-1 rounded-xl border border-line bg-surface px-3 text-[15px] outline-none focus:border-accent"
          onKeyDown={(event) => {
            // Ask needs text; Plan can run with an empty goal.
            if (event.key === 'Enter' && (isPlan || value.trim())) onSubmit()
          }}
        />
        <Button disabled={!isPlan && value.trim() === ''} onClick={onSubmit}>
          {isPlan ? 'Plan' : 'Ask'}
        </Button>
      </div>
    </Card>
  )
}

function PlanView({
  plan,
  saving,
  onSave,
}: {
  plan: CoachPlan
  saving: boolean
  onSave: () => void
}) {
  const isProgram = plan.programName !== null && plan.durationWeeks !== null
  return (
    <Card className="p-4">
      <SectionLabel>{isProgram ? 'Proposed program' : 'Proposed week'}</SectionLabel>
      {isProgram && (
        <p className="mt-1 text-[15px] font-bold tracking-tight">
          {plan.programName}
          <span className="ml-1.5 text-[12.5px] font-medium text-ink-muted">
            {plan.durationWeeks} weeks · {plan.sessions.length} sessions/week
          </span>
        </p>
      )}
      <p className="mt-1 text-[13.5px] text-ink-secondary">{plan.overview}</p>

      <div className="mt-3 space-y-3">
        {plan.sessions.map((session, si) => (
          <div key={si} className="rounded-xl border border-line">
            <p className="border-b border-line px-3 py-2 text-[14px] font-semibold">
              {session.name}
            </p>
            <div className="divide-y divide-line">
              {session.exercises.map((e, ei) => (
                <div key={ei} className="px-3 py-2">
                  <div className="flex items-baseline justify-between gap-2">
                    <span className="text-[14px] font-medium">{e.name}</span>
                    <span className="tabular shrink-0 text-[12.5px] text-ink-muted">
                      {e.sets} ×{' '}
                      {e.repLow === e.repHigh ? e.repLow : `${e.repLow}-${e.repHigh}`}
                      {e.weight !== null && ` · ${e.weight}`}
                    </span>
                  </div>
                  {e.note && (
                    <p className="mt-0.5 text-[12px] text-ink-muted">
                      {e.autoProgress && (
                        <span className="mr-1 font-semibold text-accent">↑ auto</span>
                      )}
                      {e.note}
                    </p>
                  )}
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      <p className="mt-3 text-[12px] text-ink-muted">
        Saving creates one editable template per session
        {isProgram && ` in a "${plan.programName}" folder`}. Lifts marked{' '}
        <span className="font-semibold text-accent">↑ auto</span> add weight as you clear
        the rep range. Tweak anything afterward in Templates.
      </p>
      <Button className="mt-2 w-full" disabled={saving} onClick={onSave}>
        {saving ? 'Saving…' : 'Save as templates'}
      </Button>
    </Card>
  )
}

/** The exact payload that would leave the device — the §13 consent disclosure. */
function DataDisclosure({
  summary,
  onDismiss,
}: {
  summary: CoachSummary
  onDismiss: () => void
}) {
  return (
    <BottomSheet onDismiss={onDismiss} panelClassName="max-h-[85%] overflow-y-auto">
      <div className="sticky top-0 border-b border-line bg-surface px-5 py-3.5">
        <h2 className="text-[17px] font-bold tracking-tight">Exactly what's sent</h2>
        <p className="mt-0.5 text-[12.5px] text-ink-secondary">
          No name, no dates, no notes — just these aggregates. Nothing else leaves your
          device.
        </p>
      </div>
      <pre className="overflow-x-auto px-5 py-4 text-[11.5px] leading-relaxed text-ink-secondary">
        {JSON.stringify(summary, null, 2)}
      </pre>
    </BottomSheet>
  )
}

function SectionLabel({
  children,
  className = '',
}: {
  children: React.ReactNode
  className?: string
}) {
  return (
    <p
      className={
        'text-[12px] font-semibold uppercase tracking-wide text-ink-muted ' + className
      }
    >
      {children}
    </p>
  )
}
