/**
 * The AI coach interface and its structured output (§13).
 *
 * All coach access goes through `CoachProvider`, exactly like `SyncBackend` for
 * the server: the mock and the real LLM implement the same three methods, so the
 * UI never knows which is behind it and the real provider drops in later without
 * touching a screen.
 *
 * The output is **structured, not prose** (§13): a plan deserializes straight
 * into `templates` + `template_exercises` rather than being parsed from text.
 * This is also the JSON Schema the real provider is constrained to emit.
 */

import type { CoachSummary } from './summary'

/** A single planned exercise in a coach-proposed session. */
export interface PlanExercise {
  /** The exercise name — matched to a library id when materialized. */
  name: string
  sets: number
  repLow: number
  repHigh: number
  /** Suggested working weight in the user's unit, or null to let history seed it. */
  weight: number | null
  /** One-line rationale, shown under the exercise. */
  note: string
}

/** One session in a proposed week. */
export interface PlanSession {
  /** e.g. "Push A", "Legs". Becomes the template name. */
  name: string
  exercises: PlanExercise[]
}

/** A concrete next-week plan the user can edit and save as templates. */
export interface CoachPlan {
  /** 1–2 sentence summary of the week's intent. */
  overview: string
  sessions: PlanSession[]
}

/** A critique: what's going well, what's off, and concrete suggestions. */
export interface CoachCritique {
  /** 2–4 short observations, each standalone. */
  observations: string[]
  /** Concrete, actionable suggestions. */
  suggestions: string[]
}

/** What the user asked the coach for. */
export type CoachRequest =
  { kind: 'critique' } | { kind: 'plan' } | { kind: 'question'; question: string }

/** The provider's answer, tagged by kind so the UI renders the right shape. */
export type CoachResponse =
  | { kind: 'critique'; critique: CoachCritique }
  | { kind: 'plan'; plan: CoachPlan }
  | { kind: 'answer'; text: string }

export interface CoachProvider {
  /** Human-readable provider name, for the "generated by" line. */
  readonly name: string
  /**
   * Produce a response for the request against the de-identified summary. The
   * summary is the *only* data that leaves the device (§2) — a provider must
   * never be handed anything else.
   */
  respond(summary: CoachSummary, request: CoachRequest): Promise<CoachResponse>
  /** Whether this provider can currently serve a request. */
  isAvailable(): Promise<boolean>
}
