/**
 * The AI coach interface and its structured output (§13).
 *
 * All coach access goes through `CoachProvider`, exactly like `SyncBackend` for
 * the server: the mock and the real LLM implement the same three methods, so the
 * UI never knows which is behind it and the real provider drops in later without
 * touching a screen.
 *
 * The output is **structured, not prose** (§13): a plan deserializes straight
 * into `templates` + `template_exercises` rather than being parsed from text.
 * This is also the JSON Schema the real provider is constrained to emit.
 */

import type { CoachSummary } from './summary'

/** A single planned exercise in a coach-proposed session. */
export interface PlanExercise {
  /** The exercise name — matched to a library id when materialized. */
  name: string
  sets: number
  repLow: number
  repHigh: number
  /** Suggested working weight in the user's unit, or null to let history seed it. */
  weight: number | null
  /** One-line rationale, shown under the exercise. */
  note: string
  /** Set an auto-progression rule on this exercise when saved (§7 Phase 4). */
  autoProgress?: boolean
}

/** One session — becomes one template. */
export interface PlanSession {
  /** e.g. "Push A", "Legs". Becomes the template name. */
  name: string
  exercises: PlanExercise[]
}

/**
 * A plan the user can edit and save as templates. A single-week plan has one
 * set of sessions; a multi-week program names a folder and explains the arc in
 * `overview` and per-session notes, with progression rules carrying week-to-week
 * load increases (rather than emitting one template per week per day).
 */
export interface CoachPlan {
  /** 1–3 sentence summary of the plan's intent and how to run it over time. */
  overview: string
  /** Folder name for a multi-week program, or null for a loose set of days. */
  programName: string | null
  /** Intended program length in weeks, or null for a single week. */
  durationWeeks: number | null
  sessions: PlanSession[]
}

/** A critique: what's going well, what's off, and concrete suggestions. */
export interface CoachCritique {
  /** 2–4 short observations, each standalone. */
  observations: string[]
  /** Concrete, actionable suggestions. */
  suggestions: string[]
}

/**
 * What the user asked the coach for.
 *   - critique: no input.
 *   - plan: a free-text goal ("strength-focused, 12 weeks"); may be empty.
 *   - ask: a free-text question that may itself request a plan ("give me a
 *     push day") — so the response can come back as a plan or as prose.
 */
export type CoachRequest =
  | { kind: 'critique' }
  | { kind: 'plan'; goal: string }
  | { kind: 'ask'; question: string }
  /** A warm 1–2 sentence progress note for the Home greeting. Returns `answer`. */
  | { kind: 'encouragement' }

/** The provider's answer, tagged by kind so the UI renders the right shape. */
export type CoachResponse =
  | { kind: 'critique'; critique: CoachCritique }
  | { kind: 'plan'; plan: CoachPlan }
  | { kind: 'answer'; text: string }

export interface CoachProvider {
  /** Human-readable provider name, for the "generated by" line. */
  readonly name: string
  /**
   * Produce a response for the request against the de-identified summary. The
   * summary is the *only* data that leaves the device (§2) — a provider must
   * never be handed anything else.
   */
  respond(summary: CoachSummary, request: CoachRequest): Promise<CoachResponse>
  /** Whether this provider can currently serve a request. */
  isAvailable(): Promise<boolean>
}
